version: "3.7"
services:
    database:
        container_name: "lottie-db"
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Aman
            POSTGRES__DB: lottie_assessment
        ports:
            - '5432:5432'
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
            - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
        restart: always
        networks: 
            - default

    lottie:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        networks:
            - default
        depends_on:
            - database

